// VedaLingo 90-Day Content — 60 Words · 60 Grammar · 60 Mythology
// Voice texts: max 9 words each — targets ~10s per reel
// Sanskrit words appear on screen only — never spoken (avoids pronunciation errors)
// All content is educational, non-controversial, culturally respectful.

// Helper: convert compact array to object
function r([id, deva, translit, screenText, hook, voice2, voice3, voice4]) {
  return { id, devanagari: deva, translit, screenText, hook, voice2, voice3, voice4 };
}

// ─────────────────────────────────────────────
// WORDS OF THE DAY  (60)
// ─────────────────────────────────────────────
const WORDS = [
  ['viveka',       'विवेक',        'viveka',        'discernment · the power to distinguish',
   'Sanskrit has a word English does not.',
   'The power to see what truly matters.',
   'Real from unreal. Important from urgent.',
   'That is discernment.'],

  ['ahimsa',       'अहिंसा',       'ahiṃsā',        'non-violence · harmlessness in thought and deed',
   'The most powerful force is also the gentlest.',
   'Non-violence toward every living being.',
   'Not just action — thought and speech too.',
   'Ahimsa begins within.'],

  ['satya',        'सत्य',         'satya',         'truth · that which does not change',
   'What is the one thing that never changes?',
   'Truth — not opinion, but what simply is.',
   'Sanskrit defines it as the unchanging real.',
   'Truth outlasts everything.'],

  ['dharma',       'धर्म',         'dharma',        'duty · righteousness · the path that upholds',
   'One word. No single English translation.',
   'Duty, law, nature, and righteousness — all at once.',
   'What upholds the world is called dharma.',
   'Each person has their own.'],

  ['karma',        'कर्म',         'karma',         'intentional action · not fate, but choice',
   'Karma is not punishment. It is physics.',
   'Every intentional action creates a ripple.',
   'Not fate — your choices shaping your path.',
   'You are writing it right now.'],

  ['jnana',        'ज्ञान',        'jñāna',         'knowledge · wisdom earned through understanding',
   'What is the difference between knowing and understanding?',
   'Jnana is knowledge that transforms you.',
   'Not facts memorized — truth experienced.',
   'The knowing that sets you free.'],

  ['prema',        'प्रेम',        'prema',         'love · unconditional, without expectation',
   'Sanskrit has 96 words for love.',
   'Prema is the purest form — with no conditions.',
   'Not need. Not habit. Unconditional warmth.',
   'Love without wanting anything back.'],

  ['shanti',       'शान्ति',       'śānti',         'peace · stillness within, not absence of storm',
   'Peace is not the absence of noise.',
   'Shanti is stillness that holds through the storm.',
   'An inner steadiness no outside can break.',
   'That is peace.'],

  ['ananda',       'आनन्द',        'ānanda',        'bliss · joy that arises without cause',
   'What if joy needed no reason at all?',
   'Ananda is bliss that arises from within.',
   'Not triggered by events — simply present.',
   'Your natural state, uncovered.'],

  ['seva',         'सेवा',         'sevā',          'service · giving without keeping score',
   'The oldest form of gratitude is service.',
   'Seva means giving without counting the cost.',
   'Service as a path, not an obligation.',
   'The act itself is the reward.'],

  ['kshama',       'क्षमा',        'kṣamā',         'forgiveness · releasing the burden you carry',
   'Forgiveness is not weakness in Sanskrit.',
   'Kshama means releasing what you no longer need.',
   'The one who forgives carries less weight.',
   'It is a gift to yourself.'],

  ['shraddha',     'श्रद्धा',      'śraddhā',       'faith · trust earned through inner conviction',
   'Faith in Sanskrit is more than belief.',
   'Shraddha is conviction tested and proven.',
   'Not blind trust — certainty from experience.',
   'The ground you stand on.'],

  ['sadhana',      'साधना',        'sādhanā',       'practice · daily discipline that builds the self',
   'Every master was once a consistent beginner.',
   'Sadhana is daily practice that shapes character.',
   'Small, repeated, sincere effort over time.',
   'The path itself is the goal.'],

  ['dhyana',       'ध्यान',        'dhyāna',        'meditation · sustained, unbroken attention',
   'Before focus, Sanskrit named it perfectly.',
   'Dhyana is unbroken attention without effort.',
   'Not concentration — a natural settling in.',
   'The root of Zen and Chan.'],

  ['yoga',         'योग',          'yoga',          'union · joining what was never truly separate',
   'Yoga means far more than a posture.',
   'To join — body, mind, and awareness as one.',
   'The root means to yoke or unite.',
   'Union, not exercise.'],

  ['mukti',        'मुक्ति',       'mukti',         'liberation · freedom from what binds the mind',
   'What would it feel like to be truly free?',
   'Mukti is freedom from the weight of the mind.',
   'Release from patterns, fears, and old stories.',
   'It starts with awareness.'],

  ['sankalpa',     'संकल्प',       'saṅkalpa',      'intention · a vow made with full resolve',
   'In Sanskrit, an intention is a sacred act.',
   'Sankalpa is a resolve made with full heart.',
   'Not a wish — a commitment to become.',
   'Set one. Hold it.'],

  ['vinaya',       'विनय',         'vinaya',        'humility · the grace to remain a student',
   'The wisest people share one quality.',
   'Vinaya is the humility to keep learning.',
   'Not self-erasure — grace without arrogance.',
   'The mark of every true master.'],

  ['karuna',       'करुणा',        'karuṇā',        'compassion · feeling with, not feeling sorry for',
   'There is a difference between pity and compassion.',
   'Karuna is feeling the pain of another as your own.',
   'Not sympathy from a distance — true closeness.',
   'The foundation of all kindness.'],

  ['utsaha',       'उत्साह',       'utsāha',        'enthusiasm · energy that rises from purpose',
   'What makes effort feel effortless?',
   'Utsaha is enthusiasm born from meaning.',
   'When you love what you do, energy flows.',
   'Purpose creates its own fuel.'],

  ['sahishnuta',   'सहिष्णुता',    'sahiṣṇutā',     'tolerance · the strength to hold space for difference',
   'Tolerance in Sanskrit is an active strength.',
   'Sahishnuta means holding space for what differs.',
   'Not mere endurance — genuine openness.',
   'The widest minds are the strongest.'],

  ['tapa',         'तप',           'tapa',          'disciplined effort · the heat that refines character',
   'Gold is refined by heat. So is character.',
   'Tapa is the effort that burns away the unnecessary.',
   'Difficulty chosen with purpose builds strength.',
   'Not punishment — refinement.'],

  ['sattva',       'सत्त्व',       'sattva',        'clarity · purity and balance of mind',
   'Some minds feel heavy. Others feel light.',
   'Sattva is the clear, luminous quality of mind.',
   'Balance, calm, and natural goodness.',
   'What you cultivate, you become.'],

  ['santosha',     'संतोष',        'santoṣa',       'contentment · finding enough in what is',
   'Enough is not a quantity. It is a choice.',
   'Santosha is contentment with what simply is.',
   'Not resignation — a deep, settled sufficiency.',
   'The richest people have this.'],

  ['svadhyaya',    'स्वाध्याय',    'svādhyāya',     'self-study · honest inquiry into who you are',
   'The most important subject is also the most ignored.',
   'Svadhyaya is the study of the self.',
   'Reading, reflecting, questioning your own patterns.',
   'Know yourself first.'],

  ['vairagya',     'वैराग्य',      'vairāgya',      'non-attachment · freedom from needing outcomes',
   'What would you do if you stopped needing approval?',
   'Vairagya is freedom from attachment to results.',
   'Act fully — let go of what follows.',
   'The secret of effortless action.'],

  ['abhaya',       'अभय',          'abhaya',        'fearlessness · not absence of fear, but its transcendence',
   'Fearlessness is not the absence of fear.',
   'Abhaya is fear met, understood, and moved through.',
   'The brave feel it — and act anyway.',
   'Courage is Abhaya in motion.'],

  ['rita',         'ऋत',           'ṛta',           'cosmic order · the pattern that underlies all things',
   'Even the seasons follow a rule.',
   'Rita is the natural order woven into everything.',
   'Sunrise, breath, season — all expressions of Rita.',
   'The universe keeps its own rhythm.'],

  ['maitri',       'मैत्री',       'maitrī',        'friendliness · warmth offered without agenda',
   'What does it mean to be a true friend?',
   'Maitri is warmth toward all beings, without agenda.',
   'Not selective kindness — an open attitude.',
   'The world changes when this spreads.'],

  ['mudita',       'मुदिता',       'muditā',        'sympathetic joy · happiness at others\' happiness',
   'Can you feel happy about someone else\'s success?',
   'Mudita is joy that arises for others\' joy.',
   'The opposite of envy — and far more freeing.',
   'True abundance has no competition.'],

  ['upeksha',      'उपेक्षा',      'upekṣā',        'equanimity · steady balance in all conditions',
   'Equanimity is not indifference.',
   'Upeksha is steady balance through joy and difficulty.',
   'Neither attached to good nor disturbed by bad.',
   'The still point in the turning world.'],

  ['asteya',       'अस्तेय',       'asteya',        'non-stealing · honoring what belongs to others',
   'Stealing goes beyond taking objects.',
   'Asteya means not taking what is not freely given.',
   'Credit, time, attention — all can be stolen.',
   'Give more than you take.'],

  ['aparigraha',   'अपरिग्रह',    'aparigraha',    'non-possessiveness · holding lightly what life lends',
   'Everything you own is borrowed from the world.',
   'Aparigraha means holding lightly what you have.',
   'Possess without being possessed in return.',
   'Own less. Live more.'],

  ['sanga',        'सङ्ग',         'saṅga',         'community · the people who shape who you become',
   'You become who you spend time with.',
   'Sanga is the community that forms your inner world.',
   'Sanskrit knew this thousands of years ago.',
   'Choose your company wisely.'],

  ['guru',         'गुरु',         'guru',          'teacher · one who dispels the darkness of ignorance',
   'Guru means more than teacher.',
   'The one who moves you from darkness to light.',
   'Not the one who knows most — who awakens most.',
   'Every life has at least one.'],

  ['vidya',        'विद्या',       'vidyā',         'learning · knowledge that frees rather than binds',
   'Not all knowledge is equal in Sanskrit.',
   'Vidya is the learning that sets you free.',
   'That which leads to understanding, not just data.',
   'The highest education liberates.'],

  ['buddhi',       'बुद्धि',       'buddhi',        'intellect · the faculty of clear discrimination',
   'What sits between raw impulse and wise action?',
   'Buddhi is the discerning intellect — your inner compass.',
   'It weighs, reflects, and guides decisions.',
   'Sharpen it. Consult it.'],

  ['chitta',       'चित्त',        'citta',         'mind · the field where all experience arises',
   'The mind in Sanskrit is not the brain.',
   'Chitta is the field where all experience unfolds.',
   'Memory, feeling, and thought together as one.',
   'Still the chitta, and everything clarifies.'],

  ['maya',         'माया',         'māyā',          'illusion · mistaking the temporary for the permanent',
   'Maya does not mean the world is fake.',
   'It means mistaking the changing for the permanent.',
   'We cling to what was never ours to keep.',
   'See clearly, and Maya dissolves.'],

  ['lila',         'लीला',         'līlā',          'divine play · action without burden or agenda',
   'What if life were meant to be played, not suffered?',
   'Lila is action for its own pure delight.',
   'No goal, no pressure — just complete presence.',
   'Mastery looks effortless because it is Lila.'],

  ['saundarya',    'सौन्दर्य',     'saundarya',     'beauty · harmony recognized by the awakened eye',
   'Sanskrit has a philosophy of beauty.',
   'Saundarya is harmony that the awakened eye perceives.',
   'Not just appearance — alignment and proportion.',
   'Beauty is a form of truth.'],

  ['prajna',       'प्रज्ञा',      'prajñā',        'profound wisdom · knowing that transcends intellect',
   'Intelligence and wisdom are not the same thing.',
   'Prajna is wisdom that goes beyond information.',
   'It sees whole, where intellect sees parts.',
   'The knowing that needs no proof.'],

  ['vak',          'वाक्',         'vāk',           'speech · the creative power of the spoken word',
   'Words in Sanskrit are considered sacred.',
   'Vak is speech — the power to create with sound.',
   'Every word you speak shapes your world.',
   'Use yours with care.'],

  ['smriti',       'स्मृति',       'smṛti',         'memory · what is remembered shapes who we become',
   'Memory is more than recollection.',
   'Smriti is what remains after experience passes.',
   'The stories we repeat become our identity.',
   'Choose what you remember.'],

  ['prakriti',     'प्रकृति',      'prakṛti',       'nature · the original, creative, dynamic principle',
   'Nature in Sanskrit is not just trees and rivers.',
   'Prakriti is the creative force behind all matter.',
   'Dynamic, rhythmic, and endlessly generative.',
   'You are made of it too.'],

  ['dhairya',      'धैर्य',        'dhairya',       'patience · courage that waits without losing faith',
   'Patience in Sanskrit is not passive.',
   'Dhairya is the courage to wait without losing faith.',
   'Strength that does not rush.',
   'The seed does not hurry the flower.'],

  ['drishti',      'दृष्टि',       'dṛṣṭi',         'vision · the perspective through which you see the world',
   'Two people see the same event differently.',
   'Drishti is the lens through which reality appears.',
   'Change your drishti — change what you see.',
   'Perspective is a choice.'],

  ['sneha',        'स्नेह',        'sneha',         'affection · the warm, oily tenderness of genuine care',
   'Sanskrit names the texture of loving care.',
   'Sneha is warm, affectionate tenderness — like oil on skin.',
   'Gentle, nourishing, and deeply human.',
   'The quiet love that sustains.'],

  ['artha',        'अर्थ',         'artha',         'meaning · one of four life-goals in Sanskrit thought',
   'What gives your actions meaning?',
   'Artha is purpose — meaning, wealth, and substance.',
   'One of four aims Sanskrit says life holds.',
   'Pursue meaning alongside success.'],

  ['moksha',       'मोक्ष',        'mokṣa',         'freedom · the final liberation from all limitation',
   'Sanskrit names the highest human aspiration.',
   'Moksha is ultimate freedom from all limitation.',
   'Not escape from life — full flowering within it.',
   'The fourth and final life-goal.'],

  ['tattva',       'तत्त्व',       'tattva',        'essential truth · the that-ness of a thing',
   'Sanskrit philosophy asks: what is anything really?',
   'Tattva is the essential truth or element of a thing.',
   'Not appearance — the core of what something is.',
   'Strip away the rest. What remains?'],

  ['cetana',       'चेतना',        'cetanā',        'awareness · the knowing quality behind all experience',
   'Who is aware of your own thoughts right now?',
   'Cetana is awareness itself — the knowing behind knowing.',
   'Not the content of mind but its luminous nature.',
   'That which sees, but cannot be seen.'],

  ['samatva',      'समत्व',        'samatva',       'evenness · the same quality toward all people and events',
   'Equanimity is the rarest of strengths.',
   'Samatva is evenness — the same quality toward all.',
   'Not indifference. A steady, open presence.',
   'The Gita calls it the mark of yoga.'],

  ['kama',         'काम',          'kāma',          'longing · desire as one of four sacred life-goals',
   'In Sanskrit, desire is not something to destroy.',
   'Kama is longing — one of four aims of a full life.',
   'Pleasure, love, and beauty all belong here.',
   'Honor it. Do not be consumed by it.'],

  ['brahman',      'ब्रह्म',       'brahman',       'the whole · the infinite ground of all existence',
   'Sanskrit has a word for everything at once.',
   'Brahman is the infinite ground from which all arises.',
   'Not a god — the totality itself.',
   'The ocean of which we are waves.'],

  ['svaraj',       'स्वराज्',      'svarāj',        'self-rule · freedom beginning within the individual',
   'True freedom starts with ruling oneself.',
   'Svaraj means self-governance — inner before outer.',
   'Gandhi used this word for national independence.',
   'Master yourself first.'],

  ['nirbhaya',     'निर्भय',       'nirbhaya',      'without fear · a state of open, unguarded presence',
   'Fearlessness is not the absence of danger.',
   'Nirbhaya is living open — nothing to defend or hide.',
   'When there is nothing to lose, there is nothing to fear.',
   'Truth lives here.'],

  ['om',           'ॐ',            'oṃ',            'the primordial sound · the hum of the universe itself',
   'Before language, there was sound.',
   'Om is the primordial vibration Sanskrit says underlies all.',
   'Scientists find a cosmic background hum too.',
   'Begin anything with this.'],

  ['satsanga',     'सत्सङ्ग',      'satsaṅga',      'company of the wise · conversations that elevate',
   'The fastest way to grow is to change your conversations.',
   'Satsanga is the company of truth-seekers.',
   'Not just who you know — what you discuss.',
   'Your conversations shape your mind.'],

  ['anukampa',    'अनुकम्पा',     'anukampā',      'compassion that trembles with another\'s pain',
   'Sanskrit has a word for empathy deeper than sympathy.',
   'Anukampa means to tremble along with — to feel what another feels.',
   'It is the root of all genuine kindness.',
   'True compassion is not pity — it is solidarity.'],
].map(r);

// ─────────────────────────────────────────────
// GRAMMAR GEMS  (60)
// ─────────────────────────────────────────────
const GRAMMAR = [
  ['three-numbers', 'एकवचन\nद्विवचन\nबहुवचन', 'ekavacana · dvivacana · bahuvacana',
   'Singular · Dual · Plural',
   'English has two numbers. Sanskrit has three.',
   'A special form just for pairs — the Dual.',
   'Singular. Dual. Plural.',
   'Grammar that honors what comes in pairs.'],

  ['no-articles',  'नास्ति', 'nāsti', 'no "the", no "a" — context makes it clear',
   'Sanskrit has no word for "the" or "a".',
   'Context, case, and order make meaning clear.',
   'The language trusts the listener.',
   'Fewer words — more precision.'],

  ['sov-order',    'कर्ता · कर्म · क्रिया', 'kartā · karma · kriyā', 'Subject · Object · Verb',
   'Sanskrit sentences end with the verb.',
   'Subject, Object, Verb — the natural Sanskrit order.',
   'The action is always the final word.',
   'Meaning builds toward its conclusion.'],

  ['sandhi',       'सन्धि', 'sandhi', 'sounds merge at boundaries — the rule of joining',
   'When two Sanskrit words meet, they often merge.',
   'Sandhi means junction — sounds blend at boundaries.',
   'Like "do not" becoming "don\'t" — but systematic.',
   'Sanskrit speech flows as one stream.'],

  ['samasa',       'समास', 'samāsa', 'compound words — two ideas becoming one',
   'Sanskrit creates new words by compounding old ones.',
   'Samasa joins two words into a single concept.',
   'Mahakala: great and time fused into one.',
   'One word can hold an entire philosophy.'],

  ['dhatu',        'धातु', 'dhātu', 'verbal root — ~2000 seeds from which Sanskrit grows',
   'All of Sanskrit grows from about two thousand seeds.',
   'Dhatu are the root forms underlying every word.',
   'One root, dozens of words — all related.',
   'Master the roots. Understand everything.'],

  ['vid-root',     'विद्', 'vid', 'to know — the root of veda, vidya, and video',
   'The English word "video" is actually Sanskrit.',
   'Vid means to know — shared root with video and veda.',
   'Latin, Greek, English — all carry this root.',
   'Sanskrit connects more languages than you think.'],

  ['gam-root',     'गम्', 'gam', 'to go — root of agama, gamana, and "come"',
   'How far does one Sanskrit root travel?',
   'Gam means to go — found in English "come" too.',
   'Agama, gamana, and even "come" share this root.',
   'Languages are family trees.'],

  ['eight-cases',  'अष्ट विभक्ति', 'aṣṭa vibhakti', 'eight grammatical cases — eight relationships',
   'Sanskrit nouns change form to show their role.',
   'Eight cases show who does, receives, owns, or is called.',
   'No prepositions needed — the ending does the work.',
   'The grammar is built into the word itself.'],

  ['three-genders', 'पुल्लिङ्ग\nस्त्रीलिङ्ग\nनपुंसकलिङ्ग', 'pulliṅga · strīliṅga · napuṃsakaliṅga',
   'Masculine · Feminine · Neuter',
   'Every Sanskrit noun has a gender.',
   'Masculine, feminine, and neuter — three worlds of meaning.',
   'Gender shapes how every noun behaves.',
   'The grammar reflects a philosophy of duality.'],

  ['vocative',     'सम्बोधन', 'sambodhana', 'the calling case — how Sanskrit addresses directly',
   'Sanskrit has a special form just for calling someone.',
   'The vocative case is used when directly addressing.',
   'Hey Arjuna — Sanskrit marks this grammatically.',
   'The language knows when you are speaking to someone.'],

  ['52-letters',   'द्विपञ्चाशत् वर्ण', 'dvipañcāśat varṇa', '52 letters — one unique symbol per sound',
   'English has 26 letters for far more than 26 sounds.',
   'Sanskrit has 52 — one unique letter for every sound.',
   'No ambiguity. One letter, one sound, always.',
   'The most phonetically precise alphabet ever designed.'],

  ['alphabet-order', 'अ आ इ ई उ ऊ…', 'a ā i ī u ū…', 'vowels first — ordered by the physics of sound',
   'The Sanskrit alphabet is ordered scientifically.',
   'Sounds are arranged by where they form in the mouth.',
   'Throat to lips — a map of human articulation.',
   'The most systematic alphabet in the world.'],

  ['kri-root',     'कृ', 'kṛ', 'to do — root of karma, kriya, and "create"',
   'The word karma simply means intentional doing.',
   'Kri is the root — to do, to make, to act.',
   'Karma, kriya, and even "create" trace back here.',
   'Every action is rooted in this one seed.'],

  ['man-root',     'मन्', 'man', 'to think — root of manas, mantra, and "mind"',
   'The English word "mind" and Sanskrit manas are the same.',
   'Man means to think — shared across thousands of years.',
   'Manas, mantra, mind — all from one root.',
   'Sanskrit and English are distant cousins.'],

  ['passive-voice', 'कर्मवाच्य', 'karmavācya', 'passive voice — action without a named actor',
   'Sanskrit passive voice is surprisingly elegant.',
   'The object becomes subject — the actor steps back.',
   'It is done — no one needed to claim credit.',
   'Humility built into the grammar.'],

  ['reduplication', 'द्विर्वचन', 'dvirvacana', 'doubling a root for emphasis or intensity',
   'Sanskrit repeats roots to amplify meaning.',
   'Reduplication doubles a sound for emphasis.',
   'Jagrat-jagrat: awake and fully awake.',
   'Repetition is power in Sanskrit grammar.'],

  ['nominal-sentence', 'नाम वाक्य', 'nāma vākya', 'sentences without the verb "to be"',
   'Sanskrit never says "I am happy."',
   'No verb "to be" needed — state is shown by form.',
   'The noun itself declares its condition.',
   'Being is assumed — not added.'],

  ['upasarga',     'उपसर्ग', 'upasarga', 'prefix — one small addition changes everything',
   'A prefix changes the entire meaning in Sanskrit.',
   'Upasarga is a prefix attached before a verb root.',
   'Gam means go. Ā-gam means come. Same root.',
   'Direction changes everything.'],

  ['pratyaya',     'प्रत्यय', 'pratyaya', 'suffix — the ending that completes a word\'s meaning',
   'In Sanskrit, the ending of a word carries its meaning.',
   'Pratyaya is the suffix that reveals role and relation.',
   'Same base word — different endings, different stories.',
   'Grammar lives at the end of the word.'],

  ['stha-root',    'स्था', 'sthā', 'to stand — root of sthana, sthiti, and "stand"',
   'The English word "stand" is Sanskrit in origin.',
   'Stha means to stand — root of sthana and sthiti.',
   'Stability, position, and standing all grow here.',
   'Even your posture has Sanskrit grammar.'],

  ['yuj-root',     'युज्', 'yuj', 'to yoke, to join — root of yoga and "yoke"',
   'Yoga and yoke are the same word.',
   'Yuj means to join — yoga comes directly from this root.',
   'The Sanskrit and English words are linguistic twins.',
   'Union has always been the point.'],

  ['budh-root',    'बुध्', 'budh', 'to awaken — root of buddha, bodhi, and "bud"',
   'The word buddha simply means one who has awakened.',
   'Budh means to awaken — the root of bodhi too.',
   'Even the English "bud" may share this ancestry.',
   'Awakening is a grammatical category here.'],

  ['shru-root',    'श्रु', 'śru', 'to hear — root of shruti, the heard knowledge',
   'The oldest Indian knowledge was heard, not read.',
   'Shru means to hear — root of shruti.',
   'Shruti is sacred knowledge received through listening.',
   'Before writing, wisdom was sound.'],

  ['ten-verb-classes', 'दश गण', 'daśa gaṇa', 'ten verb classes — ten families of action',
   'Sanskrit organizes all verbs into ten families.',
   'Each class has its own conjugation pattern.',
   'Once you know the class, you know the pattern.',
   'Grammar as a system, not a list.'],

  ['negation-a',   'अ / अन्', 'a / an', 'the prefix that negates — Sanskrit\'s most productive prefix',
   'One letter can negate any Sanskrit word.',
   'The prefix a- means not — ahimsa, not-himsa.',
   'Ananta, an-artha, a-satya — all follow this rule.',
   'Even English uses it: atypical, asymmetric.'],

  ['dhar-root',    'धृ', 'dhṛ', 'to hold, to uphold — root of dharma itself',
   'Dharma comes from the root meaning to hold.',
   'Dhri means to hold, to sustain, to uphold.',
   'Dharma is what holds the world together.',
   'The word carries its own definition.'],

  ['raj-root',     'राज्', 'rāj', 'to shine, to rule — root of raja and "regal"',
   'A king in Sanskrit is literally one who shines.',
   'Raj means to shine — and secondarily, to rule.',
   'Raja, royal, regal — all share this Sanskrit root.',
   'Leadership as luminosity.'],

  ['context-free', 'वाक्य स्वातन्त्र्य', 'vākya svātantrya', 'free word order — meaning held in endings, not position',
   'In Sanskrit, word order does not change meaning.',
   'Endings carry function — position carries emphasis.',
   'The same sentence rearranged says the same thing.',
   'The most flexible grammar ever structured.'],

  ['pib-root',     'पा', 'pā', 'to drink — root of pana, panaka, and "potable"',
   'The English word "potable" is Sanskrit at its root.',
   'Pa means to drink — root of pana and potable.',
   'One root crossed continents and millennia.',
   'Languages drink from the same source.'],

  ['same-root',    'सम्', 'sam', 'together — the root hidden in Sanskrit\'s own name',
   'The word Sanskrit is itself Sanskrit.',
   'Sam means together — sam plus krita means perfectly made.',
   'Sanskrit means refined, complete, perfected.',
   'A language that named itself humbly.'],

  ['svara',        'स्वर', 'svara', 'musical note · self-shining sound',
   'Sanskrit names musical notes with one word.',
   'Svara means self-shining — the note that resonates.',
   'Indian classical music is built on this concept.',
   'Sound as light, not just vibration.'],

  ['lip-root',     'लिप्', 'lip', 'to write, to smear — root of lipi, the writing system',
   'Writing in Sanskrit was once called smearing.',
   'Lip means to mark or write — root of lipi.',
   'Script, inscription, and writing all begin here.',
   'Language made visible.'],

  ['tomorrow-word', 'श्वः / परश्वः', 'śvaḥ / paraśvaḥ', 'tomorrow · the day after tomorrow — named precisely',
   'Sanskrit has a specific word for the day after tomorrow.',
   'Parashvas means exactly that — not "in two days."',
   'The language honors time with precision.',
   'Every duration has its own name.'],

  ['ten-present',  'लट् लकार', 'laṭ lakāra', 'the present tense — nine forms for one moment',
   'English has one form for present tense.',
   'Sanskrit has nine — for person and number together.',
   'I go, you go, they go — each has a unique form.',
   'Precision is built into every verb.'],

  ['agglutinative', 'समस्त पद', 'samasta pada', 'agglutinative — many meanings layered in one long word',
   'Sanskrit can express a full sentence in one word.',
   'Multiple meanings are layered into a single form.',
   'Sarvajnapratyaksha: directly perceived by the all-knowing.',
   'One word. An entire theology.'],

  ['kala-root',    'काल', 'kāla', 'time — both duration and the great equalizer',
   'Time in Sanskrit does two things at once.',
   'Kala means time — and also refers to dissolution.',
   'The same word gives and takes away.',
   'Time as teacher.'],

  ['vac-root',     'वच्', 'vac', 'to speak — root of vakya, vak, and "voice"',
   'Your voice and Sanskrit vak are the same word.',
   'Vac means to speak — root of vak and vakya.',
   'Voice, vocal, evoke — English carries this too.',
   'Speech is sacred. Use it accordingly.'],

  ['jna-root',     'ज्ञ', 'jña', 'to know — root of jnana, prajna, and "know"',
   'The English word "know" is the Sanskrit root jña.',
   'Jña means to know — root of jnana and prajna.',
   'Gnosis in Greek shares the same ancestry.',
   'Knowing is older than any one language.'],

  ['dri-root',     'दृश्', 'dṛś', 'to see — root of darshana, the philosophy of seeing',
   'In Sanskrit, philosophy is called seeing.',
   'Darshana literally means to see or behold.',
   'Indian philosophical schools are called darshanas.',
   'Insight begins with clear seeing.'],

  ['tap-root',     'तप्', 'tap', 'to heat — root of tapas, the inner fire of discipline',
   'Discipline in Sanskrit is described as inner heat.',
   'Tap means to heat — root of tapas.',
   'The English word "tepid" shares this origin.',
   'Warmth and will come from the same place.'],

  ['bhav-root',    'भू', 'bhū', 'to be, to become — root of bhavana, bhava, and "be"',
   'Even "to be" has a Sanskrit root.',
   'Bhu means to exist, to become — root of bhava.',
   'English "be," Latin "fui" — all trace back here.',
   'Existence has one root across all languages.'],

  ['sam-krita',    'संस्कृत', 'saṃskṛta', 'refined · perfected · put together completely',
   'What does the word Sanskrit actually mean?',
   'Sam plus krita — perfectly or completely made.',
   'A language that named itself as a finished work.',
   'The refined one.'],

  ['priya-root',   'प्रिय', 'priya', 'dear, beloved — a root that travels across cultures',
   'The word "price" and Sanskrit priya are cousins.',
   'Priya means dear — what is valued and beloved.',
   'Both price and prize carry this Sanskrit ancestry.',
   'Value and love share a root.'],

  ['nri-root',     'नृ', 'nṛ', 'human being — root of nara, narayana, and "man"',
   'The Sanskrit word for human is still alive in English.',
   'Nri means human — root of nara and Narayana.',
   'Latin "vir" and Sanskrit share this lineage too.',
   'Human is a category, not a hierarchy.'],

  ['arth-root',    'अर्थ', 'artha', 'meaning and wealth — purpose that sustains',
   'Sanskrit uses one word for meaning and money.',
   'Artha means both purpose and material sustenance.',
   'What sustains you should also mean something.',
   'Earn with meaning. Spend with purpose.'],

  ['panca-bhutas', 'पञ्चभूत', 'pañcabhūta', 'five elements — earth, water, fire, air, space',
   'Sanskrit names the five building blocks of existence.',
   'Earth, water, fire, air, and space — the five elements.',
   'Everything material is a combination of these.',
   'The body. The planet. The cosmos.'],

  ['purusha',      'पुरुष', 'puruṣa', 'pure consciousness · the witness behind all experience',
   'Sanskrit distinguishes matter from awareness.',
   'Purusha is pure consciousness — the witnessing self.',
   'Not the body or mind — what watches them.',
   'You are the seer, not the seen.'],

  ['agni-root',    'अग्नि', 'agni', 'fire — root of ignite, ignition, and Latin ignis',
   'The English word "ignite" is Sanskrit in origin.',
   'Agni means fire — root of Latin ignis and English ignite.',
   'Fire has carried the same name across six thousand years.',
   'The oldest word may also be the brightest.'],

  ['surya-chandra', 'सूर्य · चन्द्र', 'sūrya · candra', 'sun and moon — two celestial rhythms, two Sanskrit roots',
   'Sanskrit names the sun and moon with precision.',
   'Surya is the sun — source of light and the solar year.',
   'Chandra is the moon — linked to mind and calendar.',
   'Both still carry their names in Indian languages.'],

  ['vayu-root',    'वायु', 'vāyu', 'wind and breath — the same Sanskrit root',
   'Breath and wind share one Sanskrit name.',
   'Vayu means both wind in the world and breath in the body.',
   'Prana, pranayama — breathing as cosmic movement.',
   'The wind outside is the breath inside.'],

  ['pita-mata',    'पितृ · मातृ', 'pitṛ · mātṛ', 'father · mother — roots shared across all Indo-European languages',
   'Father and mother in Sanskrit are father and mother in English.',
   'Pita becomes father. Mata becomes mother.',
   'The same words, six thousand years apart.',
   'Family is the oldest grammar.'],

  ['sat-root',     'सत्', 'sat', 'being, truth, goodness — the root of all three',
   'Sanskrit uses one root for being, truth, and goodness.',
   'Sat means that which exists — and what is therefore true.',
   'Sattva, satya, Sanskrit itself — all branch from here.',
   'What truly is, is truly good.'],

  ['ashtanga',     'अष्टाङ्ग', 'aṣṭāṅga', 'eight-limbed — the structure behind Patanjali\'s yoga',
   'The famous eight limbs of yoga have a grammar.',
   'Ashtanga means eight limbs or eight parts.',
   'Ashta is eight. Anga is limb or aspect.',
   'Every system in Sanskrit has a counted structure.'],

  ['ananta',       'अनन्त', 'ananta', 'infinite, without end — the a- prefix at full power',
   'Sanskrit makes infinity grammatically.',
   'A plus anta — not-end — becomes ananta, the infinite.',
   'Anta means end. Ananta has none.',
   'The prefix does infinite work.'],

  ['maha',         'महा', 'mahā', 'great — a prefix that magnifies everything it touches',
   'Sanskrit has a word that makes anything great.',
   'Maha is the prefix for great or vast.',
   'Mahabharata: the great story of the Bharata dynasty.',
   'One syllable that elevates any word.'],

  ['tri-root',     'त्रि', 'tri', 'three — root of trio, triangle, and Sanskrit trinity',
   'The number three appears in Sanskrit across all of life.',
   'Tri means three — shared root with English trio.',
   'Triloky, trikala, trimurti — three worlds, times, forms.',
   'Three is the Sanskrit number of completeness.'],

  ['loka-root',    'लोक', 'loka', 'world · realm · plane of existence',
   'Sanskrit has a word for every world you could imagine.',
   'Loka means world or realm — as in Triloka, the three worlds.',
   'Loka comes from the root lok — to see. A world is what can be seen.',
   'Your mind itself is a loka — a world you inhabit.'],

  ['kama-artha',   'काम\nअर्थ', 'kāma · artha', 'desire and wealth — two of the four aims of life',
   'Sanskrit does not reject pleasure or wealth — it organises them.',
   'Kama is desire. Artha is wealth. Both are valid human goals.',
   'Sanskrit teaches that desire and wealth must be guided by dharma.',
   'A life well-lived honours all four aims — not just one.'],

  ['sakshi',       'साक्षी', 'sākṣī', 'the witness — the part of you that simply observes',
   'Every thought you have is watched by something deeper.',
   'Sakshi means witness — the awareness that watches the mind.',
   'The sakshi is never disturbed — only the mind is.',
   'Observe your thoughts; you are not your thoughts.'],
].map(r);

// ─────────────────────────────────────────────
// MYTHOLOGY MOMENTS  (60)
// All stories focus on character, wisdom, and courage — not religious doctrine.
// ─────────────────────────────────────────────
const MYTHS = [
  ['maryada',      'मर्यादा\nपुरुषोत्तम', 'maryādā puruṣottama',
   'The highest among men who upholds the boundary',
   'Why is Rama called the perfect man?',
   'He never broke a single promise.',
   'Even when it cost him everything.',
   'That is the standard.'],

  ['nachiketa',    'नचिकेता', 'naciketa',
   'the boy who asked death the only question worth asking',
   'A young boy faced death and asked one question.',
   'What lies beyond this life? Teach me.',
   'Yama tested him three times. He never wavered.',
   'Wisdom requires the courage to ask.'],

  ['savitri',      'सावित्री', 'sāvitrī',
   'the woman who followed death and argued her husband back',
   'She followed death itself into the forest.',
   'Savitri spoke so wisely that Yama relented.',
   'Not magic — pure clarity and love.',
   'Devotion and intelligence together are unstoppable.'],

  ['ekalavya',     'एकलव्य', 'ekalavya',
   'the student who taught himself and surpassed the taught',
   'He was refused admission to the great school.',
   'He taught himself — and became a master.',
   'His dedication shamed those who had every advantage.',
   'The best teacher is sincere practice.'],

  ['sudama',       'सुदामा', 'sudāmā',
   'the poorest friend who received the greatest welcome',
   'He arrived with nothing but a handful of rice.',
   'His childhood friend received him as a king.',
   'Old friendship needs no wealth to justify.',
   'True friendship does not forget.'],

  ['hanuman',      'हनुमान्', 'hanumān',
   'the one whose strength was only awakened by purpose',
   'He forgot he was the most powerful being there.',
   'Only purpose reminded him of what he could do.',
   'His strength was always there — waiting for a worthy aim.',
   'Purpose unlocks what talent alone cannot.'],

  ['valmiki',      'वाल्मीकि', 'vālmīki',
   'the poet who transformed himself through a single question',
   'He began as a man who harmed others.',
   'One encounter changed his question — and his life.',
   'He became the first Sanskrit poet.',
   'Transformation is always possible.'],

  ['dhruva',       'ध्रुव', 'dhruva',
   'the child who wanted what could never be taken away',
   'A young child was refused his father\'s lap.',
   'He went into the forest to earn what could not be given.',
   'He found something even Yama could not touch.',
   'Seek what no one can take from you.'],

  ['prahlad',      'प्रह्लाद', 'prahlāda',
   'the boy whose conviction survived every attempt to break it',
   'Everything was done to break his faith.',
   'Fire, water, and serpents — none could reach him.',
   'What is held within cannot be touched from without.',
   'Inner conviction is the strongest armor.'],

  ['ashtavakra',   'अष्टावक्र', 'aṣṭāvakra',
   'the crooked sage who held the straightest wisdom',
   'He was born with eight physical deformities.',
   'When the court laughed, he taught them something.',
   'The wisest voice in the room came from the strangest body.',
   'Do not judge the vessel. Hear the message.'],

  ['janaka',       'जनक', 'janaka',
   'the philosopher-king who ruled without being ruled by ruling',
   'He was a king who lived as a sage.',
   'Complete in action — untouched by result.',
   'His kingdom was proof that wisdom and leadership can coexist.',
   'Duty done without ego is the highest art.'],

  ['vishwamitra',  'विश्वामित्र', 'viśvāmitra',
   'the warrior who became a sage through relentless practice',
   'He was born a warrior and a king.',
   'He became a sage — through pure determination.',
   'The title he wanted took lifetimes to earn.',
   'Discipline can change what birth cannot.'],

  ['yudhishthira', 'युधिष्ठिर', 'yudhiṣṭhira',
   'the king who answered every question with truth',
   'At the end of the forest, he faced impossible questions.',
   'He answered each one with complete honesty.',
   'The truth he spoke opened every door.',
   'Integrity is its own reward.'],

  ['shakuntala',   'शकुन्तला', 'śakuntalā',
   'the woman forgotten by the man who loved her — and what followed',
   'He forgot her the moment a curse took his memory.',
   'She kept her dignity and raised their child alone.',
   'When he remembered — it was her grace that forgave.',
   'Character is what you do when no one remembers.'],

  ['karna',        'कर्ण', 'karṇa',
   'the warrior who gave until there was nothing left to give',
   'Even knowing the cost, he gave to every person who asked.',
   'At the moment of his death, he gave his last possession.',
   'Generosity was not his strategy — it was his nature.',
   'Some people give because they cannot do otherwise.'],

  ['arjuna',       'अर्जुन', 'arjuna',
   'the warrior who paused before the battle to ask why',
   'At the moment of greatest power, he stopped.',
   'He put down his bow and asked the deepest question.',
   'That pause gave the world the Bhagavad Gita.',
   'Hesitation can be the beginning of wisdom.'],

  ['bhishma',      'भीष्म', 'bhīṣma',
   'the man who kept a vow the world begged him to break',
   'He made a vow and kept it his entire life.',
   'Everyone around him urged him to let it go.',
   'He held it — because a promise is a promise.',
   'Integrity is not measured by convenience.'],

  ['draupadi',     'द्रौपदी', 'draupadī',
   'the woman whose question the court could not answer',
   'She asked one question in the middle of an injustice.',
   'No one in that great assembly could answer her.',
   'Silence in the face of wrong is its own verdict.',
   'A single clear question can expose everything.'],

  ['narada',       'नारद', 'nārada',
   'the wandering sage who taught through story and paradox',
   'He carried no permanent home and needed none.',
   'He taught by asking the question no one else would.',
   'The greatest teacher is sometimes also a troublemaker.',
   'Wisdom often arrives in unexpected forms.'],

  ['markandeya',   'मार्कण्डेय', 'mārkāṇḍeya',
   'the boy whose devotion defeated the certainty of death',
   'He was told he would die at sixteen.',
   'He devoted every day to something larger than himself.',
   'When death arrived, it found someone who had already lived fully.',
   'How you spend your days is how you spend your life.'],

  ['sita',         'सीता', 'sītā',
   'the woman who chose a forest over a palace — and why that matters',
   'She chose hardship alongside loyalty.',
   'The comfort of a palace could not hold her.',
   'Her choice revealed more than any crown could.',
   'Character shows itself in what you refuse.'],

  ['gajendra',     'गजेन्द्र', 'gajendra',
   'the elephant-king whose pride dissolved into surrender',
   'He fought with all his strength for a very long time.',
   'Then he stopped fighting and simply called out for help.',
   'The moment he released pride, help arrived.',
   'Surrender is not weakness. It is wisdom.'],

  ['abhimanyu',    'अभिमन्यु', 'abhimanyu',
   'the young warrior who entered alone and never looked for a way out',
   'He knew how to enter. He never learned to exit.',
   'He entered anyway — alone, and without complaint.',
   'Courage is not absence of danger — it is knowing and going.'],

  ['samudra',      'समुद्र मन्थन', 'samudra manthana',
   'the churning of the ocean — and what comes up with the nectar',
   'Gods and demons churned the ocean together.',
   'Poison emerged before nectar.',
   'The most valuable things come after the most difficult.',
   'Do not stop churning when it gets hard.'],

  ['agastya',      'अगस्त्य', 'agastya',
   'the sage who swallowed the ocean to help those who needed it',
   'Demons hid in the ocean where no one could reach them.',
   'Agastya drank the entire ocean — then the demons were found.',
   'Sometimes the problem requires an impossible solution.',
   'Extraordinary problems need extraordinary willingness.'],

  ['satyakama',    'सत्यकाम', 'satyakāma',
   'the student whose honesty earned him more than any lineage could',
   'He applied to a great teacher and was asked his family.',
   'He said honestly: I do not know.',
   'The teacher accepted him immediately.',
   'Honesty is the highest qualification.'],

  ['vasishtha',    'वसिष्ठ', 'vasiṣṭha',
   'the sage who met his ancient rival and found a friend',
   'They were rivals for most of their lives.',
   'Through long years, respect replaced rivalry.',
   'Even the deepest antagonism can find its way to friendship.',
   'Time softens what ego hardens.'],

  ['kalidasa',     'कालिदास', 'kālidāsa',
   'the poet who went from ignorance to immortality through grace',
   'He began his life unable to read or write.',
   'One encounter, one moment of openness — and everything changed.',
   'He became Sanskrit\'s greatest poet.',
   'Potential is always closer than it seems.'],

  ['shibi',        'शिबि', 'śibi',
   'the king who gave his own flesh to protect the vulnerable',
   'A dove was being chased by a hawk and sought his protection.',
   'He gave his own flesh rather than break his promise.',
   'A king\'s word was worth a kingdom.',
   'Protection without cost is not protection.'],

  ['ashwattha',    'अश्वत्थ', 'aśvattha',
   'the upside-down tree — the world seen differently in the Gita',
   'The Gita describes a tree with roots above and branches below.',
   'The world upside-down — seen from beyond it.',
   'Change your vantage point and everything shifts.',
   'Wisdom sometimes requires a reversal of perspective.'],

  ['rantideva',    'रन्तिदेव', 'rantideva',
   'the king who gave his last meal away and found everything',
   'He had fasted for forty-eight days.',
   'When food finally arrived, he gave it all away.',
   'Each visitor who came, he gave what they needed.',
   'The most generous moment is often the hardest.'],

  ['maitreyi',     'मैत्रेयी', 'maitreyī',
   'the philosopher-wife who chose wisdom over inheritance',
   'Her husband offered to leave her all his wealth.',
   'She asked: will this wealth make me immortal?',
   'When told no — she asked for wisdom instead.',
   'Know what you are really seeking.'],

  ['gargi',        'गार्गी', 'gārgī',
   'the woman who questioned the greatest sage until he asked her to stop',
   'She stood in an assembly of sages and debated the greatest of them.',
   'Her questions were so precise he had no more answers.',
   'He asked her to stop — or her head would fall off.',
   'The sharpest minds ask the questions others won\'t.'],

  ['poison-nectar', 'विष · अमृत', 'viṣa · amṛta',
   'poison and nectar — what the same effort can produce',
   'The same churning produced both poison and nectar.',
   'Someone had to hold the poison so others could reach the nectar.',
   'The willingness to take difficulty is itself a gift.',
   'Every creation has its cost.'],

  ['lakshman-rekha', 'लक्ष्मण रेखा', 'lakṣmaṇa rekhā',
   'the line drawn to protect — and what it means to cross a boundary',
   'He drew a line and said: do not cross this.',
   'The line was crossed — and everything changed.',
   'Some boundaries exist for profound reasons.',
   'Respect the line. Even when you cannot see why.'],

  ['hanuman-leap', 'लङ्कोल्लङ्घन', 'laṅkollaṅghana',
   'the impossible leap — what looks impossible from the shore',
   'He stood at the shore of an uncrossable ocean.',
   'Others had given up. He was reminded of his strength.',
   'He leaped — and the impossible became a step.',
   'The obstacle was always the path.'],

  ['jatayu',       'जटायु', 'jaṭāyu',
   'the old bird who fought a king for what was right',
   'He was old. He knew he could not win.',
   'He fought anyway — for something more important than victory.',
   'He died having done exactly what was right.',
   'Doing right does not require winning.'],

  ['vidura',       'विदुर', 'vidura',
   'the minister who spoke truth to power — every time',
   'He served a king who rarely followed his advice.',
   'He gave it anyway — clearly, honestly, every time.',
   'Wisdom is not responsible for whether it is received.',
   'Speak truth. The rest is not yours to control.'],

  ['uttanka',      'उत्तङ्क', 'uttaṅka',
   'the student who waited years for one teaching — and never complained',
   'He served his teacher for years before his lesson came.',
   'He waited. He worked. He did not ask when.',
   'The lesson, when it came, was worth every day of waiting.',
   'Some teachings arrive only in their own time.'],

  ['yajnavalkya',  'याज्ञवल्क्य', 'yājñavalkya',
   'the sage who said: I am not the body, not the mind — then who?',
   'A king offered wealth to whoever was wisest.',
   'One sage accepted immediately — and earned it.',
   'His greatest teaching: I am the witness behind all experience.',
   'The one who knows cannot be fully known.'],

  ['pandavas',     'पाण्डव', 'pāṇḍava',
   'five brothers — five different strengths completing one another',
   'Five brothers who should have been rivals — were not.',
   'Each brought what the others lacked.',
   'Together they could survive anything.',
   'Complementary strengths beat singular genius.'],

  ['harishchandra', 'हरिश्चन्द्र', 'hariścandra',
   'the king who lost everything — and never once lied',
   'He lost his kingdom, his family, and his dignity.',
   'At every point he could have lied and recovered.',
   'He never did — and his truth eventually restored everything.',
   'Integrity survives what convenience cannot.'],

  ['nala-damayanti', 'नल · दमयन्ती', 'nala · damayantī',
   'the couple who found each other twice — by character alone',
   'He lost everything and disguised himself completely.',
   'She recognized him not by his face but by who he was.',
   'Character cannot be concealed.',
   'Who you are always shows through.'],

  ['urvashi',      'उर्वशी', 'urvaśī',
   'the story of love, pride, and its limits',
   'A great love was broken by a moment of pride.',
   'Neither cruelty nor indifference — just a boundary reached.',
   'Even the deepest love has terms.',
   'Know what you are willing to offer.'],

  ['amba',         'अम्बा', 'ambā',
   'the woman whose dharma was broken — and what followed across lifetimes',
   'She was taken from her wedding by someone else\'s vow.',
   'Her righteous anger became a force that waited lifetimes.',
   'Even justice sometimes works on a long timeline.',
   'Wrong done in one life can unravel another.'],

  ['sahadeva',     'सहदेव', 'sahadeva',
   'the one who knew the future but was forbidden from speaking it',
   'He knew what would happen — he had been told.',
   'A curse prevented him from sharing what he knew.',
   'He watched events unfold that he could not prevent.',
   'Knowing is not the same as being able to act.'],

  ['dog-heaven',   'स्वर्गारोहण', 'svargārohaṇa',
   'the dog that followed Yudhishthira to heaven — and what that meant',
   'At the gate of heaven, he was told to leave his dog behind.',
   'He refused to enter without his faithful companion.',
   'The gate opened. The dog had been a god all along.',
   'Loyalty is tested at the threshold, not on the road.'],

  ['shantiparva',  'शान्तिपर्व', 'śāntiparva',
   'the book of peace — what the victors asked after the war',
   'After the greatest war ever fought, the victor asked one thing.',
   'He asked not about wealth or power — but about peace.',
   'The Shantiparva is the longest book of the Mahabharata.',
   'Victory means nothing without wisdom about what to do next.'],

  ['krishna-advice', 'निष्काम कर्म', 'niṣkāma karma',
   'act fully — let go of what follows',
   'Do the work. Release the result.',
   'Act with complete effort and no attachment to outcome.',
   'This is the final teaching of the Gita.',
   'Full action. Open hands.'],

  ['drona-eklavya', 'गुरुदक्षिणा', 'gurudakṣiṇā',
   'the price a teacher asked — and what it reveals about power',
   'The student gave everything his teacher asked.',
   'The teacher asked for the very thing that made him great.',
   'Power sometimes demands what it should protect.',
   'Notice who benefits from your sacrifice.'],

  ['bhima-yudhishthira', 'बल · सत्य', 'bala · satya',
   'strength and truth — two brothers who needed each other',
   'One had the strength. One had the truth.',
   'Neither could succeed alone.',
   'Power without ethics destroys. Ethics without power cannot protect.',
   'The two together change history.'],

  ['devavrata',    'देवव्रत', 'devavrata',
   'the man who became Bhishma — the weight of an absolute vow',
   'He gave up what he loved most to fulfill a promise.',
   'His name changed because his vow was so total.',
   'Bhishma means one who has taken a terrible vow.',
   'What you commit to fully becomes your identity.'],

  ['parvati-tapas', 'पार्वती तपस्', 'pārvatī tapas',
   'the goddess who earned through discipline what could not be given as a gift',
   'She wanted something that could not simply be offered.',
   'She earned it through years of practice and discipline.',
   'Even the gods earn what they most desire.',
   'Nothing worthy is simply handed over.'],

  ['nala-gambling', 'द्यूतक्रीडा', 'dyūtakrīḍā',
   'the game that lost a kingdom — and what addiction looks like in mythology',
   'He was the best at everything except one thing.',
   'That one weakness lost him everything.',
   'Even the greatest can be undone by a single blind spot.',
   'Know your weakness before the game begins.'],

  ['shikhandi',    'शिखण्डी', 'śikhaṇḍī',
   'the warrior whose transformation became the turning point of a great war',
   'He was born one way and became another.',
   'His transformation became the key to ending the war.',
   'What others saw as limitation became the decisive strength.',
   'Transformation is always available.'],

  ['arjuna-bow',   'गाण्डीव', 'gāṇḍīva',
   'Arjuna\'s bow — and what it means to be named for your instrument',
   'His bow had a name. He was inseparable from it.',
   'He is also called Savyasachi — the ambidextrous one.',
   'A true master and their tool become one.',
   'What is your Gandiva?'],

  ['raikva',       'रैक्व', 'raikva',
   'the cart-driver philosopher who knew more than the priest',
   'A king searched everywhere for the wisest person.',
   'He found him sleeping under a cart.',
   'The wisest voice was also the most overlooked.',
   'Look past the obvious place.'],

  ['king-shikhandi-2', 'सत्याग्रह', 'satyāgraha',
   'holding firmly to truth — the weapon that requires no violence',
   'The most powerful weapon in the Sanskrit tradition needs no sharpening.',
   'Satyagraha: holding firmly to what is true.',
   'Truth as both shield and sword — with no blood.',
   'Gandhi found this principle in the oldest texts.'],

  ['vidura-wisdom',  'विदुर', 'vidura',
   'the minister who spoke truth to power — and kept his honour',
   'One man in the Mahabharata refused to be silent.',
   'Vidura warned the king again and again — truth was not welcome.',
   'He chose his conscience over his comfort.',
   'Courage is speaking the truth when silence is safer.'],

  ['savitri-boon',   'सावित्री', 'sāvitrī',
   'the woman who followed death itself — and won back her husband',
   'She walked into the forest of death without fear.',
   'Savitri followed Yama, the god of death, for three days.',
   'Her wisdom and devotion made even death relent.',
   'Love that persists through the impossible — that is Savitri.'],
].map(r);

// ─────────────────────────────────────────────
// 90-DAY SCHEDULE
// Pattern per 3 days: [Word+Grammar] [Grammar+Myth] [Myth+Word]
// 30 cycles × 3 days = 90 days
// Each type appears exactly 60 times (2 per cycle)
// ─────────────────────────────────────────────
function buildSchedule() {
  const schedule = [];
  let wi = 0, gi = 0, mi = 0;
  for (let d = 1; d <= 90; d++) {
    const mod = (d - 1) % 3;
    let reel1, reel2;
    if (mod === 0) {
      reel1 = { type: 'word',    data: WORDS[wi++]   };
      reel2 = { type: 'grammar', data: GRAMMAR[gi++] };
    } else if (mod === 1) {
      reel1 = { type: 'grammar', data: GRAMMAR[gi++] };
      reel2 = { type: 'myth',    data: MYTHS[mi++]   };
    } else {
      reel1 = { type: 'myth',    data: MYTHS[mi++]   };
      reel2 = { type: 'word',    data: WORDS[wi++]   };
    }
    schedule.push({ day: d, reel1, reel2 });
  }
  return schedule;
}

module.exports = { WORDS, GRAMMAR, MYTHS, buildSchedule };
